name: "[compiler] Chaos C Extension Feature Tests"

on: [push, pull_request]

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y valgrind
        sudo make requirements
        sudo make requirements-dev

    - name: Build (gcc)
      run: |
        make clean
        make
        sudo make install

    - name: Run the tests (gcc)
      run: |
        make test-compiler-extensions-linux-gcc
        rm tests/extensions/spells/example/example.so

    - name: Build (clang)
      run: |
        make clean
        make clang
        sudo make install

    - name: Run the tests (clang)
      run: |
        make test-compiler-extensions-linux-clang
        rm tests/extensions/spells/example/example.so

  macos:
    name: macos
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: |
        mv /usr/local/bin/gcc-8 /usr/local/bin/gcc
        make requirements
        make requirements-dev

    - name: Build (gcc)
      run: |
        source ~/.bash_profile
        make clean
        make
        make install

    - name: Run the tests (gcc)
      run: |
        source ~/.bash_profile
        make test-compiler-extensions-macos-gcc
        rm tests/extensions/spells/example/example.dylib

    - name: Build (clang)
      run: |
        source ~/.bash_profile
        make clean
        make clang
        make install

    - name: Run the tests (clang)
      run: |
        make test-compiler-extensions-macos-clang
        rm tests/extensions/spells/example/example.dylib

  windows:
    name: windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      shell: cmd
      run: |
        call make.bat requirements
        call make.bat requirements-dev

    - name: Build (gcc)
      shell: cmd
      run: |
        call make.bat clean
        call make.bat
        call make.bat install

    - name: Run the tests (gcc)
      shell: cmd
      run: |
        call make.bat test-compiler-extensions-windows-gcc
        del tests\extensions\spells\example\example.dll

    - name: Build (clang)
      shell: cmd
      run: |
        call RefreshEnv.cmd
        call make.bat clean
        call make.bat clang
        call make.bat install

    - name: Run the tests (clang)
      shell: cmd
      run: |
        call RefreshEnv.cmd
        call make.bat test-compiler-extensions-windows-clang
        del tests\extensions\spells\example\example.dll
